### ISSUE TITLE
requirement for the file named 'base_options'

### ISSUE THREAD

**Issue by Amazingren** [PangzeCheung/Dual-task-Pose-Transformer-Network#1]
Hey @PangzeCheung ,
Thanks for your impressive work, It's really interesting, I want to reproduce the results. However, when I want to re-train the model by meself, I find there should one files named ```base_option.py``` missed. Could you kindly add the file? 

Many Thanks

**Comment by PangzeCheung** [comment]
Thank you for your attention. I have uploaded the file base_option.py.

**Comment by Amazingren** [comment]
> Thank you for your attention. I have uploaded the file base_option.py.

Thanks for you very rapid reley, it's really nice the problem is solved now.

Best Regards
