### ISSUE TITLE
New image test

### ISSUE THREAD

**Issue by xiaoyanLi629** [PangzeCheung/Dual-task-Pose-Transformer-Network#10]
Hello, I am wondering how to test on unseen image. I followed the procedure and I found I need to generate keypoints for my images. I found the PATN project >> tool/compute_coordiantes.py. But when I run this file on my image, there is an error says the size mismatch which caused at line 216. (output1, output2 = model.predict(imageToTest_padded)). It looks like because of the multiplier, the input sizes are different, so there always an error. I am wondering how to solve this problem?

Thank you!

**Comment by PangzeCheung** [comment]
> Hello, I am wondering how to test on unseen image. I followed the procedure and I found I need to generate keypoints for my images. I found the PATN project >> tool/compute_coordiantes.py. But when I run this file on my image, there is an error says the size mismatch which caused at line 216. (output1, output2 = model.predict(imageToTest_padded)). It looks like because of the multiplier, the input sizes are different, so there always an error. I am wondering how to solve this problem?
> 
> Thank you!

Hi Li, I don't know much about these settings in PATN. Maybe you can try to resize the image to the size of images in DeepFashion to avoid such a problem. In addition, other open source pose estimators that can predict 18 keypoints (such as OpenPose, Alphapose, etc.) are also available to provide pose input for this project. You can try to change different pose estimators to fix this issue.

**Comment by xiaoyanLi629** [comment]
> > Hello, I am wondering how to test on unseen image. I followed the procedure and I found I need to generate keypoints for my images. I found the PATN project >> tool/compute_coordiantes.py. But when I run this file on my image, there is an error says the size mismatch which caused at line 216. (output1, output2 = model.predict(imageToTest_padded)). It looks like because of the multiplier, the input sizes are different, so there always an error. I am wondering how to solve this problem?
> > Thank you!
> 
> Hi Li, I don't know much about these settings in PATN. Maybe you can try to resize the image to the size of images in DeepFashion to avoid such a problem. In addition, other open source pose estimators that can predict 18 keypoints (such as OpenPose, Alphapose, etc.) are also available to provide pose input for this project. You can try to change different pose estimators to fix this issue.

I tried to resize the images, but in the code, it resize each image by a few factors in a loop. It looks like the model takes in variable size images but it didn't work. I also tried other keypoint extractors but the order is important. The keypoints extratced by other methods doesnt work for this one.

**Comment by PangzeCheung** [comment]
> > > Hello, I am wondering how to test on unseen image. I followed the procedure and I found I need to generate keypoints for my images. I found the PATN project >> tool/compute_coordiantes.py. But when I run this file on my image, there is an error says the size mismatch which caused at line 216. (output1, output2 = model.predict(imageToTest_padded)). It looks like because of the multiplier, the input sizes are different, so there always an error. I am wondering how to solve this problem?
> > > Thank you!
> > 
> > 
> > Hi Li, I don't know much about these settings in PATN. Maybe you can try to resize the image to the size of images in DeepFashion to avoid such a problem. In addition, other open source pose estimators that can predict 18 keypoints (such as OpenPose, Alphapose, etc.) are also available to provide pose input for this project. You can try to change different pose estimators to fix this issue.
> 
> I tried to resize the images, but in the code, it resize each image by a few factors in a loop. It looks like the model takes in variable size images but it didn't work. I also tried other keypoint extractors but the order is important. The keypoints extratced by other methods doesnt work for this one.

Hi Li, I have tried to test PATN using the keypoints provided by offical OpenPose and AlphaPose in our preliminary work, and everything worked fine.  If your keypoints are not in the PATN's format, you can try adjusting the keypoint order as following: ['nose', 'neck', 'Rsho', 'Relb', 'Rwri', 'Lsho', 'Lelb', 'Lwri', 'Rhip', 'Rkne', 'Rank', 'Lhip', 'Lkne', 'Lank', 'Leye', 'Reye', 'Lear', 'Rear'].
