### ISSUE TITLE
evaluation dataset preparation

### ISSUE THREAD

**Issue by gkalstn000** [PangzeCheung/Dual-task-Pose-Transformer-Network#11]
Hi, can you check if the data set I prepared is correct?
I cannot understand [GFLA's](https://github.com/RenYurui/Global-Flow-Local-Attention) evaluation setting.

I did,
[gt_path] dataset : (750 x 1101) -> (176, 256).  *using `PIL.Image.resize((176, 256))`
[fid_real_path] dataset : (750 x 1101) -> (176, 256).  *using `PIL.Image.resize((176, 256))`

Every scores are lower than on paper.
Do I have to resize images by using`cv2.resize` method?

**Comment by PangzeCheung** [comment]
@gkalstn000 Sorry for the late reply.  DPTN follows the data processing of PATN, which is different from that of the GFLA. Same as PATN, we use the low-resolution (256 x 256) deepfashion dataset, while the GFLA uses the high-resolution  (750 x 1101) version. Hope this will clear up your problem.

**Comment by gkalstn000** [comment]
Thank you for your reply. I got almost the same eval score compared to the paper.
