### ISSUE TITLE
testing on Market

### ISSUE THREAD

**Issue by khadijakhaldi** [PangzeCheung/Dual-task-Pose-Transformer-Network#12]
I'm testing the pretrained model on the market dataset (by following the steps), but am getting gray images. 
Please can you advice ?
![images](https://user-images.githubusercontent.com/25855062/202600516-c8a2be46-fb1d-423e-95cb-1d7c123f46d0.png)

**Comment by khadijakhaldi** [comment]
apparently https://github.com/PangzeCheung/Dual-task-Pose-Transformer-Network/blob/10c858001f446601f73b46b9300c5ce10cf1fd3f/models/DPTN_model.py#L113 returns fake_image_t as matrix of nan

**Comment by gkalstn000** [comment]
you have to download pre-trained model and put it on checkpoints/[name]/
![image](https://user-images.githubusercontent.com/26128046/202943698-9667a8b7-7a84-4bdf-a2b3-74df3a234212.png)

**Comment by PangzeCheung** [comment]
Thanks @gkalstn000 for the reply.  Also thanks for your question @khadijakhaldi, you can confirm whether the pre-trained model is loaded correctly.

**Comment by khadijakhaldi** [comment]
yes, it is working!
Thanks.
