### ISSUE TITLE
Test results on Deepfashion

### ISSUE THREAD

**Issue by Arvohy** [PangzeCheung/Dual-task-Pose-Transformer-Network#14]
Hi, thanks for your enlightened work. Do the released "epoch-190" images correspond to the results in the paper?
I calculate the metrics on the images and it seems different from those in the paper. Is the metrics figure related to the version of software and GPU?
![ac5ee43b26ee5dd2cb3dcd940d0c209](https://user-images.githubusercontent.com/67821445/223077556-f0b27e89-0446-4fc8-becd-2e8f4a15c94b.png)

**Comment by soon-yau** [comment]
I have also just tried epoch-190 and the images look bad. Did you look at the generated images?

**Comment by Arvohy** [comment]
![image](https://user-images.githubusercontent.com/67821445/223296163-d6be06f5-25ff-4c4d-b227-6540440ec0a7.png)
![1678152773119](https://user-images.githubusercontent.com/67821445/223296180-8be3e811-df53-4bd4-860a-258b3c86db08.jpg)
I just unzip your released test results and conduct evaluation.

**Comment by Arvohy** [comment]
> I have also just tried epoch-190 and the images look bad. Did you look at the generated images?
![image](https://user-images.githubusercontent.com/67821445/223298089-6a4f2493-9f46-4c1e-b643-898ce9e8dbf7.png)
Yeah, the generated images look common. And then I try to use the released test results and conduct evaluation.
![image](https://user-images.githubusercontent.com/67821445/223296163-d6be06f5-25ff-4c4d-b227-6540440ec0a7.png)
![1678152773119](https://user-images.githubusercontent.com/67821445/223296180-8be3e811-df53-4bd4-860a-258b3c86db08.jpg)

**Comment by PangzeCheung** [comment]
@Arvohy Thank you for your attention. The "epoch-190" images that we have released are consistent with the results presented in our paper. Our preprocessing method is identical to the PATN method, which uses 256 * 256 images instead of high-resolution image datasets. It is possible that the differences observed in your results may be attributed to the use of different preprocessing methods.

**Comment by Arvohy** [comment]
@PangzeCheung I use your released "metrics.py" code and the resized 256 * 176 images (from the raw 256 * 256 images) for evaluation. I feel confused that my evaluation results are different from many other papers. 😢

**Comment by IMSEMZPZ** [comment]
@Arvohy For fair comparison, our released "metrics.py" code follows the DIST method (https://github.com/RenYurui/Global-Flow-Local-Attention/blob/master/script/metrics.py). The only difference is that the SSIM and PSNR score are calculated by padding the image to 256*256 (follows PATN).  I hope this information proves helpful to you~

**Comment by PangzeCheung** [comment]
@Arvohy For fair comparison, our released "metrics.py" code follows the DIST method (https://github.com/RenYurui/Global-Flow-Local-Attention/blob/master/script/metrics.py). The only difference is that the SSIM and PSNR score are calculated by padding the image to 256*256 (follows PATN). I hope this information proves helpful to you~

**Comment by Arvohy** [comment]
@PangzeCheung Thank you for your detailed answer.🙇‍
