### ISSUE TITLE
Fashion result looks terrible

### ISSUE THREAD

**Issue by soon-yau** [PangzeCheung/Dual-task-Pose-Transformer-Network#15]
![fashionWOMENBlouses_Shirtsid0000523301_1front_2_fashionWOMENBlouses_Shirtsid0000523301_4full_vis](https://user-images.githubusercontent.com/19167278/223181668-7f44a762-b57a-4c18-b2be-df5f713ef9ef.jpg)

I downloaded the model and run inference. By the way, the image pre-processing file did not work straight away, had to make some changes to get the path name correct. Anyway, the image results I got look aweful, not just a few, but all of them. Have I done anything wrong? 

I unzip epoch190.zip into `checkpoints/DPTN_fashion` and run
`python test.py --name=DPTN_fashion --model=DPTN --dataset_mode=fashion --dataroot=./dataset/fashion --which_epoch latest --results_dir ./results/DPTN_fashion --batchSize 1 --gpu_id=0`

**Comment by PangzeCheung** [comment]
@soon-yau Thanks for your attention. Our preprocessing method is identical to the PATN method, which employs 256 * 256 images rather than high-resolution image datasets. I hope this information proves helpful to you~
