### ISSUE TITLE
About the training epochs?

### ISSUE THREAD

**Issue by Blackkinggg** [PangzeCheung/Dual-task-Pose-Transformer-Network#3]
How many epochs should I train to get the results you shown in the paper. It seems need 140 epochs, which will cost 1 week. I use one Tesla V100-32g in training time, and when using multiple gpus, there will be serious load imbalance.

**Comment by PangzeCheung** [comment]
Thanks for your attention. We did not optimize the load imbalance caused by multi GPU training. For Deepfashion, DPTN does take around 200 epochs to train (over one week on NVIDIA A100 40GB PCIe). Results may converge after 170 epochs (see Figure 6 in our paper).

**Comment by PangzeCheung** [comment]
> How many epochs should I train to get the results you shown in the paper. It seems need 140 epochs, which will cost 1 week. I use one Tesla V100-32g in training time, and when using multiple gpus, there will be serious load imbalance.

Thanks for your attention. We did not optimize the load imbalance caused by multi GPU training. For Deepfashion, DPTN does take around 200 epochs to train (over one week on NVIDIA A100 40GB PCIe). Results may converge after 170 epochs (see Figure 6 in our paper).
