### ISSUE TITLE
training step problem

### ISSUE THREAD

**Issue by xieyipeng** [PangzeCheung/Dual-task-Pose-Transformer-Network#4]
* Your work inspires me a lot！
* It is mentioned in the text that train the `source-to-source` network as an auxiliary, and then share the weights to the `source-to-target`, I would like to know their training steps?
* First ignore the `Pose Transformer Module`, train the `source-to-source` network, then share parameters to the `source-to-target` network, and finally train the `Pose Transformer Module`.
* Is that what I think? I want to know more details！
* Thank u a lot!

**Comment by PangzeCheung** [comment]
Thanks for your interest. Our DPTN is trained in an end-to-end manner, which means the source-to-source and source-to-target networks are trained simultaneously.  You can refer to our code for more details.

**Comment by xieyipeng** [comment]
ok,thank u!
