### ISSUE TITLE
why the fid calculated with your evaluation script is different from the fid on your paper?

### ISSUE THREAD

**Issue by mlyarthur** [PangzeCheung/Dual-task-Pose-Transformer-Network#7]
![image](https://user-images.githubusercontent.com/29242717/172323705-daf2a69c-5f9c-4c99-bb1c-cf4c4244b85b.png)
I just use the generated results that you provide  and the metrics calculation scripts. But the fid is not same with the one on your paper.
![image](https://user-images.githubusercontent.com/29242717/172324133-6fa79074-0256-43f7-a82d-4f514ba87d9c.png)

**Comment by IMSEMZPZ** [comment]
您好，我是Pangze Cheung。我已经收到您的邮件，我会尽快回复您的！谢谢！-------------------------------------------------------------------------------------------------------------Best Wishes For YouPangze Cheung

**Comment by mlyarthur** [comment]
my anaconda environment 
![image](https://user-images.githubusercontent.com/29242717/172329386-bc4f73b5-4f8e-403a-b578-af83f4017b8f.png)

**Comment by PangzeCheung** [comment]
@mlyarthur Thanks for your attention.  We have retested the FID score of our generated image as shown in Figure (FID: 11.4556), which is consistent with the results of our paper. Based on the information you provided, it's also hard for me to know why you're getting this result. Our evalution script is same as the DIST, maybe you can find more information from ( https://github.com/RenYurui/Global-Flow-Local-Attention).

![647 WTB~A93 4QYW1O2%B5F](https://user-images.githubusercontent.com/37894893/172336253-43532b57-27bc-4875-84fe-09ccb79210c3.png)

**Comment by mlyarthur** [comment]
@PangzeCheung Thanks for your quick reply. can you give me your email to ask more detailed questions? i followed the DIST data and evaluation pipeline, but the evaluation result is still weird.

**Comment by mlyarthur** [comment]
are you calculate the fid with the training set ()?
image below is the my  fashion training image with id fashionMENDenimid0000008001_1front.jpg. can you help me to check if it is same as yours. 
![fashionMENDenimid0000008001_1front](https://user-images.githubusercontent.com/29242717/172344098-b29765b5-d86b-4991-8a9c-26df1c0732e0.jpg)

**Comment by PangzeCheung** [comment]
@mlyarthur We following DIST, and calculate the FID score with the training set. Also, your fashionMENDenimid0000008001_1front.jpg is same as mine.
