### ISSUE TITLE
FID calculation: what is the number of generated images used to calculate FID?

### ISSUE THREAD

**Issue by ankanbhunia** [PangzeCheung/Dual-task-Pose-Transformer-Network#9]
Can you confirm if this work used the standard practice to calculate the FID: 50K generated images as _fake_ and whole training set as _real_?

**Comment by PangzeCheung** [comment]
@ankanbhunia Thanks for your attention. Following DIST, our evalution script is same as the code in (https://github.com/RenYurui/Global-Flow-Local-Attention). Specifically, for DeepFashion, following PATN, 8,570 pairs are used for testing. Therefore, when calculating FID, the 8570 generated images are used as fake, and whole training set  are used as real.
